name: mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  tag_name: mirror-run-${{ github.run_id }}

jobs:
  mirror-keydb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download file
        run: curl -O http://fvonline-db.bplaced.net/export/keydb_eng.zip
      
      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keydb
          path: keydb_eng.zip
          
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.tag_name }}
          force_push_tag: true

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: keydb_eng.zip
          tag_name: ${{ env.tag_name }}
